In [1]:
import numpy as np
import pandas as pd

In [3]:
pd.__version__

'1.4.4'

In [15]:
table=pd.read_csv('alexeyhousing.csv')
table

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [38]:
table['total_bedrooms'].isnull().sum()

207

In [29]:
n=table.groupby(by=['ocean_proximity']).mean()
n

longitude   latitude  housing_median_age  total_rooms  \
ocean_proximity                                                           
<1H OCEAN       -118.847766  34.560577           29.279225  2628.343586   
INLAND          -119.732990  36.731829           24.271867  2717.742787   
ISLAND          -118.354000  33.358000           42.400000  1574.600000   
NEAR BAY        -122.260694  37.801057           37.730131  2493.589520   
NEAR OCEAN      -119.332555  34.738439           29.347254  2583.700903   

                 total_bedrooms   population  households  median_income  \
ocean_proximity                                                           
<1H OCEAN            546.539185  1520.290499  517.744965       4.230682   
INLAND               533.881619  1391.046252  477.447565       3.208996   
ISLAND               420.400000   668.000000  276.600000       2.744420   
NEAR BAY             514.182819  1230.317467  488.616157       4.172885   
NEAR OCEAN           538.615677  1354.008653  501.244545       4.005785   

                 median_house_value  
ocean_proximity                      
<1H OCEAN             240084.285464  
INLAND                124805.392001  
ISLAND                380440.000000  
NEAR BAY              259212.311790  
NEAR OCEAN            249433.977427

In [31]:
n['median_house_value']['NEAR BAY']

259212.31179039303

In [42]:
n['total_bedrooms']['NEAR BAY']

514.1828193832599

In [50]:
t=table['total_bedrooms'].fillna(round(n['total_bedrooms']['NEAR BAY'],3))
t.mean()

537.6329884205442

In [51]:
table['total_bedrooms'].mean()
#changed

537.8705525375618

In [53]:
island=table[table['ocean_proximity']=='ISLAND']
island = island[['housing_median_age','total_rooms','total_bedrooms']]

In [56]:
X=np.array(island)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [60]:
XTX = np.matmul(X.T,X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [61]:
y=[950, 1300, 800, 1000, 1300]

In [66]:
w=np.matmul(np.matmul(np.linalg.inv(XTX),X.T),y)
w

array([23.12330961, -1.48124183,  5.69922946])